name: Linting and Tests
on:
  push:
    branches: ["master", "main", "develop"]
  pull_request:

jobs: 
  check-code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install tox
      - run: tox -e check_codestyle

  check-types:
    name: Check types with Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install tox
      - run: tox -e check_types

  unit-tests:
    name: Unit tests
    # If you want to require linting to run first, uncomment this line:
    #needs: [lint]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install tox
      - run: tox -e tests

